/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author iured
 */
public class IndexFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IndexFrame.class.getName());

    /**
     * Creates new form IndexFrame
     */
    public IndexFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
        // Mostrar painel de lista de pedidos por padrão
        java.awt.CardLayout clPedidos = (java.awt.CardLayout) painelPedidos.getLayout();
        clPedidos.show(painelPedidos, "card2");
        
        // Mostrar painel de lista de sapatos por padrão
        java.awt.CardLayout clSapatos = (java.awt.CardLayout) painelSapatos.getLayout();
        clSapatos.show(painelSapatos, "card2");
        
        // Adicionar listener ao botão "Novo Pedido"
        painelPedidosLista1.getBtnCriarPedido().addActionListener(e -> {
            System.out.println("Botão 'Novo Pedido' clicado!");
            clPedidos.show(painelPedidos, "card3");
            painelPedidos.revalidate();
            painelPedidos.repaint();
        });
        
        // Adicionar listener ao botão "Voltar" do formulário de pedidos
        painelPedidosForm1.getBtnVoltar().addActionListener(e -> {
            System.out.println("Botão 'Voltar' clicado!");
            clPedidos.show(painelPedidos, "card2");
            painelPedidos.revalidate();
            painelPedidos.repaint();
        });
        
        // Adicionar listener ao botão "Novo Sapato"
        painelSapatosLista1.getBtnCriarSapato().addActionListener(e -> {
            System.out.println("Botão 'Novo Sapato' clicado!");
            clSapatos.show(painelSapatos, "card1");
            painelSapatos.revalidate();
            painelSapatos.repaint();
        });
        
        // Adicionar listener ao botão "Voltar" do formulário de sapatos
        painelSapatosForm1.getBtnVoltarSapatos().addActionListener(e -> {
            System.out.println("Botão 'Voltar Sapatos' clicado!");
            clSapatos.show(painelSapatos, "card2");
            painelSapatos.revalidate();
            painelSapatos.repaint();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abas = new javax.swing.JTabbedPane();
        painelPedidos = new javax.swing.JPanel();
        painelPedidosForm1 = new gui.PainelPedidosForm();
        painelPedidosLista1 = new gui.PainelPedidosLista();
        painelSapatos = new javax.swing.JPanel();
        painelSapatosForm1 = new gui.PainelSapatosForm();
        painelSapatosLista1 = new gui.PainelSapatosLista();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPedidos.setLayout(new java.awt.CardLayout());

        painelPedidosForm1.setPreferredSize(new java.awt.Dimension(881, 446));
        painelPedidos.add(painelPedidosForm1, "card3");

        painelPedidosLista1.setPreferredSize(new java.awt.Dimension(881, 446));
        painelPedidos.add(painelPedidosLista1, "card2");

        abas.addTab("Pedidos", painelPedidos);

        painelSapatos.setLayout(new java.awt.CardLayout());

        painelSapatosForm1.setPreferredSize(new java.awt.Dimension(881, 446));
        painelSapatos.add(painelSapatosForm1, "card1");

        painelSapatosLista1.setPreferredSize(new java.awt.Dimension(881, 446));
        painelSapatos.add(painelSapatosLista1, "card2");

        abas.addTab("Sapatos", painelSapatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IndexFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abas;
    private javax.swing.JPanel painelPedidos;
    private gui.PainelPedidosForm painelPedidosForm1;
    private gui.PainelPedidosLista painelPedidosLista1;
    private javax.swing.JPanel painelSapatos;
    private gui.PainelSapatosForm painelSapatosForm1;
    private gui.PainelSapatosLista painelSapatosLista1;
    // End of variables declaration//GEN-END:variables
}
