/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author iured
 */
public class IndexFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IndexFrame.class.getName());

    /**
     * Creates new form IndexFrame
     */
    public IndexFrame() {
        initComponents();
        
        painelPedidosLista1 = new PainelPedidosLista();
        painelPedidosForm1 = new PainelPedidosForm();
        painelSapatosLista1 = new PainelSapatosLista();
        painelSapatosForm1 = new PainelSapatosForm();
        
        // Adicionar as cartas do CardLayout de Pedidos
        painelPedidos.add(painelPedidosForm1, "card3");
        painelPedidos.add(painelPedidosLista1, "card2");
        
        // Adicionar as cartas do CardLayout de Sapatos
        painelSapatos.add(painelSapatosForm1, "card1");
        painelSapatos.add(painelSapatosLista1, "card2");
        
        setLocationRelativeTo(null);
        setSize(900, 520);
        
        java.awt.CardLayout clPedidos = (java.awt.CardLayout) painelPedidos.getLayout();
        clPedidos.show(painelPedidos, "card2");
        
        java.awt.CardLayout clSapatos = (java.awt.CardLayout) painelSapatos.getLayout();
        clSapatos.show(painelSapatos, "card2");
        
        painelPedidosLista1.configurarReferencias(painelPedidos, painelPedidosForm1);
        painelSapatosLista1.configurarReferencias(painelSapatos, painelSapatosForm1);
        
        painelPedidosLista1.getBtnCriarPedido().addActionListener(e -> {
            painelPedidosForm1.limparCampos();
            clPedidos.show(painelPedidos, "card3");
            painelPedidos.revalidate();
            painelPedidos.repaint();
        });
        
        painelPedidosForm1.getBtnVoltar().addActionListener(e -> {
            clPedidos.show(painelPedidos, "card2");
            painelPedidos.revalidate();
            painelPedidos.repaint();
        });

        painelPedidosForm1.getBtnSalvarPedido().addActionListener(e -> {
            painelPedidosForm1.salvarPedido();
            painelPedidosLista1.carregarPedidos();
            clPedidos.show(painelPedidos, "card2");
            painelPedidos.revalidate();
            painelPedidos.repaint();
        });

        painelPedidosForm1.getBtnLimparPedido().addActionListener(e -> {
            painelPedidosForm1.limparCampos();
        });

        painelPedidosLista1.getBtnBuscaPedidos().addActionListener(e -> {
            String termo = painelPedidosLista1.getCampoBuscaPedidos().getText();
            painelPedidosLista1.buscarPedidos(termo);
        });
        
        painelSapatosLista1.getBtnCriarSapato().addActionListener(e -> {
            painelSapatosForm1.limparCampos();
            clSapatos.show(painelSapatos, "card1");
            painelSapatos.revalidate();
            painelSapatos.repaint();
        });
        
        painelSapatosForm1.getBtnVoltarSapatos().addActionListener(e -> {
            clSapatos.show(painelSapatos, "card2");
            painelSapatos.revalidate();
            painelSapatos.repaint();
        });

        painelSapatosForm1.getBtnSalvarSapato().addActionListener(e -> {
            painelSapatosForm1.salvarSapato();
            painelSapatosLista1.carregarSapatos();
            clSapatos.show(painelSapatos, "card2");
            painelSapatos.revalidate();
            painelSapatos.repaint();
        });

        painelSapatosForm1.getBtnLimparSapato().addActionListener(e -> {
            painelSapatosForm1.limparCampos();
        });

        painelSapatosLista1.getBtnBuscarSapato().addActionListener(e -> {
            String termo = painelSapatosLista1.getCampoBuscaSapato().getText();
            painelSapatosLista1.buscarSapatos(termo);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abas = new javax.swing.JTabbedPane();
        painelPedidos = new javax.swing.JPanel();
        painelPedidosForm1 = new gui.PainelPedidosForm();
        painelPedidosLista1 = new gui.PainelPedidosLista();
        painelSapatos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPedidos.setLayout(new java.awt.CardLayout());

        abas.addTab("Pedidos", painelPedidos);

        painelSapatos.setLayout(new java.awt.CardLayout());
        abas.addTab("Sapatos", painelSapatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(abas, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IndexFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abas;
    private javax.swing.JPanel painelPedidos;
    private gui.PainelPedidosForm painelPedidosForm1;
    private gui.PainelPedidosLista painelPedidosLista1;
    private javax.swing.JPanel painelSapatos;
    private gui.PainelSapatosForm painelSapatosForm1;
    private gui.PainelSapatosLista painelSapatosLista1;
    // End of variables declaration//GEN-END:variables
}
