/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.PedidoDAO;
import models.Pedido;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author gerlandoprado
 */
public class PainelPedidosLista extends javax.swing.JPanel {

    /**
     * Creates new form PainelPedidosLista
     */
    public PainelPedidosLista() {
        initComponents();
        carregarPedidos();
        configurarColunas();
    }

    private void configurarColunas() {
        // Cliente (coluna 1) com largura maior
        tablePedidos.getColumnModel().getColumn(1).setPreferredWidth(150);
        // Data (coluna 2)
        tablePedidos.getColumnModel().getColumn(2).setPreferredWidth(80);
        // Quantidade (coluna 3)
        tablePedidos.getColumnModel().getColumn(3).setPreferredWidth(80);
        // Preço Total (coluna 4)
        tablePedidos.getColumnModel().getColumn(4).setPreferredWidth(90);
        // Sapato (coluna 5)
        tablePedidos.getColumnModel().getColumn(5).setPreferredWidth(80);
        // Ações (coluna 6)
        tablePedidos.getColumnModel().getColumn(6).setPreferredWidth(80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPedidos = new javax.swing.JPanel();
        boxPedidos = new javax.swing.JPanel();
        btnCriarPedido = new javax.swing.JButton();
        campoBuscaPedidos = new javax.swing.JTextField();
        btnBuscaPedidos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblPedidos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePedidos = new javax.swing.JTable();

        btnCriarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/add.png"))); // NOI18N
        btnCriarPedido.setText("Novo pedido");

        campoBuscaPedidos.setColumns(35);

        btnBuscaPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/pesquisar.png"))); // NOI18N
        btnBuscaPedidos.setText("Buscar");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");

        javax.swing.GroupLayout boxPedidosLayout = new javax.swing.GroupLayout(boxPedidos);
        boxPedidos.setLayout(boxPedidosLayout);
        boxPedidosLayout.setHorizontalGroup(
            boxPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoBuscaPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscaPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCriarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        boxPedidosLayout.setVerticalGroup(
            boxPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxPedidosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(campoBuscaPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boxPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCriarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscaPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator1)
        );

        lblPedidos.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblPedidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPedidos.setText("Listagem de Pedidos");

        tablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Cliente", "Data", "Quantidade", "Preço Total", "Sapato", "Ações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePedidos);

        javax.swing.GroupLayout painelPedidosLayout = new javax.swing.GroupLayout(painelPedidos);
        painelPedidos.setLayout(painelPedidosLayout);
        painelPedidosLayout.setHorizontalGroup(
            painelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boxPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelPedidosLayout.setVerticalGroup(
            painelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boxPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxPedidos;
    private javax.swing.JButton btnBuscaPedidos;
    private javax.swing.JButton btnCriarPedido;
    private javax.swing.JTextField campoBuscaPedidos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblPedidos;
    private javax.swing.JPanel painelPedidos;
    private javax.swing.JTable tablePedidos;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnCriarPedido() {
        return btnCriarPedido;
    }

    public javax.swing.JButton getBtnBuscaPedidos() {
        return btnBuscaPedidos;
    }

    public javax.swing.JTable getTablePedidos() {
        return tablePedidos;
    }

    public javax.swing.JTextField getCampoBuscaPedidos() {
        return campoBuscaPedidos;
    }

    public void carregarPedidos() {
        try {
            PedidoDAO pedidoDAO = new PedidoDAO();
            List<Pedido> pedidos = pedidoDAO.listPedido();
            
            DefaultTableModel model = (DefaultTableModel) tablePedidos.getModel();
            model.setRowCount(0); // Limpa linhas anteriores
            
            for (Pedido pedido : pedidos) {
                Object[] row = {
                    pedido.getPED_CODIGO(),
                    pedido.getPED_CLIENTE(),
                    pedido.getPED_DATA(),
                    pedido.getPED_QUANTIDADE(),
                    String.format("%.2f", pedido.getPED_PRECO_TOTAL()),
                    pedido.getSAP_CODIGO(),
                    "Ações"
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            System.err.println("Erro ao carregar pedidos: " + e.getMessage());
            e.printStackTrace();
        }
    }

    public void buscarPedidos(String termo) {
        try {
            DefaultTableModel model = (DefaultTableModel) tablePedidos.getModel();
            model.setRowCount(0);
            
            if (termo == null || termo.isEmpty()) {
                carregarPedidos();
                lblPedidos.setText("Listagem de Pedidos");
                return;
            }
            
            // Filtrar pedidos por cliente
            PedidoDAO pedidoDAO = new PedidoDAO();
            List<Pedido> pedidos = pedidoDAO.listPedido();
            
            for (Pedido pedido : pedidos) {
                if (pedido.getPED_CLIENTE().toLowerCase().contains(termo.toLowerCase())) {
                    Object[] row = {
                        pedido.getPED_CODIGO(),
                        pedido.getPED_CLIENTE(),
                        pedido.getPED_DATA(),
                        pedido.getPED_QUANTIDADE(),
                        String.format("%.2f", pedido.getPED_PRECO_TOTAL()),
                        pedido.getSAP_CODIGO(),
                        "Ações"
                    };
                    model.addRow(row);
                }
            }
            
            lblPedidos.setText("Resultados de busca para: " + termo);
        } catch (Exception e) {
            System.err.println("Erro ao buscar pedidos: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
