/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.SapatoDAO;
import models.Sapato;
import javax.swing.JOptionPane;

/**
 *
 * @author gerlandoprado
 */
public class PainelSapatosForm extends javax.swing.JPanel {

    private Integer sapatoCodigoEdicao = null;

    /**
     * Creates new form PainelSapatosForm
     */
    public PainelSapatosForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblFornecedor = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        lblPrecoCompra = new javax.swing.JLabel();
        txtPrecoCompra = new javax.swing.JTextField();
        lblPrecoVenda = new javax.swing.JLabel();
        txtPrecoVenda = new javax.swing.JTextField();
        lblQuantidade = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnVoltarSapatos = new javax.swing.JButton();
        btnSalvarSapato = new javax.swing.JButton();
        btnLimparSapato = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Formulário de Sapato");

        lblNome.setText("Nome:");

        lblFornecedor.setText("Fornecedor:");

        lblPrecoCompra.setText("Preço Compra:");

        lblPrecoVenda.setText("Preço Venda:");

        lblQuantidade.setText("Quantidade:");

        btnVoltarSapatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/voltar.png"))); // NOI18N
        btnVoltarSapatos.setText("Voltar");

        btnSalvarSapato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/salvar.png"))); // NOI18N
        btnSalvarSapato.setText("Salvar");

        btnLimparSapato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/limpar.png"))); // NOI18N
        btnLimparSapato.setText("Limpar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltarSapatos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNome)
                                .addComponent(lblFornecedor))
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                                .addComponent(txtNome)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblQuantidade)
                            .addGap(18, 18, 18)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(lblPrecoCompra)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                            .addComponent(lblPrecoVenda)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(btnLimparSapato, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnSalvarSapato, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltarSapatos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lblFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPrecoCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLimparSapato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalvarSapato, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimparSapato;
    private javax.swing.JButton btnSalvarSapato;
    private javax.swing.JButton btnVoltarSapatos;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPrecoCompra;
    private javax.swing.JLabel lblPrecoVenda;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPrecoCompra;
    private javax.swing.JTextField txtPrecoVenda;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnVoltarSapatos() {
        return btnVoltarSapatos;
    }

    public javax.swing.JButton getBtnSalvarSapato() {
        return btnSalvarSapato;
    }

    public javax.swing.JButton getBtnLimparSapato() {
        return btnLimparSapato;
    }

    public void salvarSapato() {
        try {
            if (txtNome.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, preencha o nome do sapato!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtFornecedor.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, preencha o fornecedor!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtPrecoCompra.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, preencha o preço de compra!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtPrecoVenda.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, preencha o preço de venda!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (txtQuantidade.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, preencha a quantidade!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Sapato sapato = new Sapato();
            
            if (sapatoCodigoEdicao != null) {
                sapato.setSAP_CODIGO(sapatoCodigoEdicao);
            }
            
            sapato.setSAP_NOME(txtNome.getText());
            sapato.setSAP_FORNECEDOR(txtFornecedor.getText());
            sapato.setSAP_PRECO_COMPRA(Double.parseDouble(txtPrecoCompra.getText().replace(",", ".")));
            sapato.setSAP_PRECO_VENDA(Double.parseDouble(txtPrecoVenda.getText().replace(",", ".")));
            sapato.setSAP_QUANTIDADE(Integer.parseInt(txtQuantidade.getText()));

            SapatoDAO sapatoDAO = new SapatoDAO();
            
            if (sapatoCodigoEdicao != null) {
                sapatoDAO.updateSapato(sapato);
                JOptionPane.showMessageDialog(this, "Sapato atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                sapatoDAO.saveSapato(sapato);
                JOptionPane.showMessageDialog(this, "Sapato salvo com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            }
            
            limparCampos();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Formato inválido! Verifique preços e quantidade.", "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    public void limparCampos() {
        txtNome.setText("");
        txtFornecedor.setText("");
        txtPrecoCompra.setText("");
        txtPrecoVenda.setText("");
        txtQuantidade.setText("");
        sapatoCodigoEdicao = null;
    }

    public void carregarSapatoParaEdicao(int codigo) {
        try {
            SapatoDAO sapatoDAO = new SapatoDAO();
            Sapato sapato = sapatoDAO.getSapato(codigo);
            
            if (sapato != null) {
                sapatoCodigoEdicao = sapato.getSAP_CODIGO();
                txtNome.setText(sapato.getSAP_NOME());
                txtFornecedor.setText(sapato.getSAP_FORNECEDOR());
                txtPrecoCompra.setText(String.format("%.2f", sapato.getSAP_PRECO_COMPRA()));
                txtPrecoVenda.setText(String.format("%.2f", sapato.getSAP_PRECO_VENDA()));
                txtQuantidade.setText(String.valueOf(sapato.getSAP_QUANTIDADE()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar sapato: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
}
