/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author gerlandoprado
 */
public class PainelSapatosLista extends javax.swing.JPanel {

    /**
     * Creates new form PainelSapatosLista
     */
    public PainelSapatosLista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSapatos = new javax.swing.JPanel();
        boxSapatos = new javax.swing.JPanel();
        btnCriarSapato = new javax.swing.JButton();
        campoBuscaSapato = new javax.swing.JTextField();
        btnBuscarSapato = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        javax.swing.JLabel lblSapatos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSapatos = new javax.swing.JTable();

        btnCriarSapato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/add.png"))); // NOI18N
        btnCriarSapato.setText("Novo sapato");
        btnCriarSapato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarSapatoActionPerformed(evt);
            }
        });

        campoBuscaSapato.setColumns(35);
        campoBuscaSapato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscaSapatoActionPerformed(evt);
            }
        });

        btnBuscarSapato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/pesquisar.png"))); // NOI18N
        btnBuscarSapato.setText("Buscar");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setToolTipText("");

        javax.swing.GroupLayout boxSapatosLayout = new javax.swing.GroupLayout(boxSapatos);
        boxSapatos.setLayout(boxSapatosLayout);
        boxSapatosLayout.setHorizontalGroup(
            boxSapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxSapatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoBuscaSapato, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarSapato, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCriarSapato, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        boxSapatosLayout.setVerticalGroup(
            boxSapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxSapatosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(campoBuscaSapato, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxSapatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boxSapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCriarSapato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarSapato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jSeparator2)
        );

        lblSapatos.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSapatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSapatos.setText("Listagem de Sapatos");

        tableSapatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Fornecedor", "Preço de compra", "Preço de venda", "Quantidade", "Ações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableSapatos);

        javax.swing.GroupLayout painelSapatosLayout = new javax.swing.GroupLayout(painelSapatos);
        painelSapatos.setLayout(painelSapatosLayout);
        painelSapatosLayout.setHorizontalGroup(
            painelSapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boxSapatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(painelSapatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSapatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        painelSapatosLayout.setVerticalGroup(
            painelSapatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSapatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boxSapatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSapatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelSapatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelSapatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarSapatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarSapatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCriarSapatoActionPerformed

    private void campoBuscaSapatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscaSapatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaSapatoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxSapatos;
    private javax.swing.JButton btnBuscarSapato;
    private javax.swing.JButton btnCriarSapato;
    private javax.swing.JTextField campoBuscaSapato;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel painelSapatos;
    private javax.swing.JTable tableSapatos;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnCriarSapato() {
        return btnCriarSapato;
    }

    public javax.swing.JButton getBtnBuscarSapato() {
        return btnBuscarSapato;
    }

    public javax.swing.JTable getTableSapatos() {
        return tableSapatos;
    }

    public javax.swing.JTextField getCampoBuscaSapato() {
        return campoBuscaSapato;
    }
}
